name = "VScript"
grammar = "vscript"
path_suffixes = ["vs"]
line_comments = ["//"]
block_comment = ["/*", "*/"]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = "string" },
  { start = "'", end = "'", close = true, newline = false, not_in = "string" }
]
tab_size = 4
hard_tabs = false
