[package]
name = "zed-vscript"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "<1.0.0"
thiserror = "2.0.0"

# [profile]
# lto = "thin"
