id = "vscript"
name = "VScript"
description = "Support for the VScript programming language"
version = "0.1.0"
schema_version = 1
authors = ["github.com/m-epasta"]
repository = "https://github.com/m-epasta/zed-vscript"

[grammars.vscript]
repository = "https://github.com/m-epasta/vscript-tree-sitter"
commit = "4f752c7"

[language_servers.vscript]
languages = ["vscript"]
name = "LanguageServer.vs"
