id = "vscript"
name = "VScript"
description = "Support for the VScript programming language"
version = "0.1.0"
schema_version = 1
authors = ["github.com/m-epasta"]
repository = "https://github.com/m-epasta/zed-vscript"

[grammars.vscript]
path = "grammars/vscript"
