id = "vscript"
name = "VScript"
description = "Support for the VScript programming language"
version = "0.1.0"
schema_version = 1
authors = ["github.com/m-epasta"]
repository = "https://github.com/m-epasta/zed-vscript"

[grammars.vscript]
repository = "https://github.com/m-epasta/vscript-tree-sitter"
commit = "c73489dcde48eba65ae20f7394c0ba022a101506"

[language_servers.vscript]
languages = ["vscript"]
name = "vscript-lsp"

[slash_commands]
vslp-logs = { description = "View VScript LSP logs", requires_argument = false }

[tasks."vslp: view logs"]
command = "cat /tmp/vslp.log"
