id = "vscript"
name = "VScript"
description = "Support for the VScript programming language"
version = "0.1.0"
schema_version = 1
authors = ["github.com/m-epasta"]
repository = "https://github.com/m-epasta/zed-vscript"

[grammars.vscript]
repository = "file:///home/m-epasta/vscript_repo/zed-vscript"
rev = "201685131e6383d6b94cbb82763a1ca1d2bf8fc4"
path = "grammars/vscript"
