id = "vscript"
name = "VScript"
description = "Support for the VScript programming language"
version = "0.1.0"
schema_version = 1
authors = ["github.com/m-epasta"]
repository = "https://github.com/m-epasta/zed-vscript"

[grammars.vscript]
repository = "https://github.com/m-epasta/vscript-tree-sitter"
commit = "158d6f2ad6bd57f2436dcf8d3a514b51433fb079"

[language_servers.vscript]
languages = ["vscript"]
name = "vscript-lsp"
download_url = "https://github.com/m-epasta/vslp/releases/download/latest/vslp"
