id = "vscript"
name = "VScript"
description = "Support for the VScript programming language"
version = "0.1.0"
schema_version = 1
authors = ["github.com/m-epasta"]
repository = "https://github.com/m-epasta/zed-vscript"

[grammars.vscript]
repository = "https://github.com/m-epasta/vscript-tree-sitter"
commit = "43c27d9f3fe768241e22939634db379b1ccca3eb"

[language_servers.vscript]
languages = ["vscript"]
name = "vscript-lsp"
download_url = "https://github.com/m-epasta/vslp/releases/download/latest/vslp"
